name: Build and Deploy to Kubernetes

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/my-web-app:latest
          ${{ secrets.DOCKER_USERNAME }}/my-web-app:${{ github.sha }}
        
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        
    - name: Add EC2 to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        
    - name: Deploy to Kubernetes
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          # Create namespace if it doesn't exist
          kubectl create namespace my-web-app --dry-run=client -o yaml | kubectl apply -f -
          
          # Create deployment YAML
          cat << 'DEPLOY_EOF' > /home/ubuntu/web-app-deployment.yaml
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: my-web-app
            namespace: my-web-app
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: my-web-app
            template:
              metadata:
                labels:
                  app: my-web-app
              spec:
                containers:
                - name: my-web-app
                  image: ${{ secrets.DOCKER_USERNAME }}/my-web-app:${{ github.sha }}
                  ports:
                  - containerPort: 80
                  resources:
                    requests:
                      memory: "64Mi"
                      cpu: "50m"
                    limits:
                      memory: "128Mi"
                      cpu: "100m"
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: my-web-app-service
            namespace: my-web-app
          spec:
            selector:
              app: my-web-app
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80
                nodePort: 30080
            type: NodePort
          DEPLOY_EOF
          
          # Apply the deployment
          kubectl apply -f /home/ubuntu/web-app-deployment.yaml
          
          # Wait for deployment to be ready
          kubectl rollout status deployment/my-web-app -n my-web-app --timeout=300s
          
          # Show deployment status
          echo "Deployment completed successfully!"
          kubectl get pods -n my-web-app
          kubectl get svc -n my-web-app
          
          # Show access information
          PUBLIC_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)
          echo "=========================================="
          echo "🎉 Your web app is now accessible at:"
          echo "http://$PUBLIC_IP:30080"
          echo "=========================================="
        EOF
